config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  resources :issues
  resources :articles
  resources :projects
  resources :facts

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :issue
end

app/models/fact.rb
class Fact < ActiveRecord::Base
	belongs_to :project
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :articles
  has_many :projects
  has_many :facts,	through: :projects

  def to_s
  	topic
  end
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :issue
  has_many :facts
  
  def to_s
  	project_title
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
	end

	def index
		@article = Article.find(params[:id])
	end

end

app/controllers/facts_controller.rb
class FactsController < ApplicationController

	def index
		@facts = Fact.all
	end

	def show 
		@fact = Fact.find(params[:id])
	end

end 

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
  	@articles = Article.all
  	@issues = Issue.all
  	@projects = Project.all
  end

  def show
  	@issue = Issue.find(params[:id])
  	@issueimage = @issue.imageurl 

	@articletitle = @issue.articles.collect(&:title) 
	@articleurl = @issue.articles.collect(&:article_url) 
	@articletitle = @issue.articles.collect(&:title) 
	@articleimage = @issue.articles.collect(&:imageurl) 
	@articleauthor = @issue.articles.collect(&:author) 
	@articlelead = @issue.articles.collect(&:lead) 
	@articlepublication = @issue.articles.collect(&:publication) 
	@articledate = @issue.articles.collect(&:published_on)
	@articleimagecredit = @issue.articles.collect(&:imagecredit) 
	
	@projecttype = @issue.projects.collect(&:projecttype)	
	@projecturl = @issue.projects.collect(&:project_url) 
	@projecttitle = @issue.projects.collect(&:project_title) 
	@projectorg = @issue.projects.collect(&:organization) 
	@projectsumm = @issue.projects.collect(&:summary) 
	@projectimage = @issue.projects.collect(&:imageurl) 

	@facttext = @issue.facts.collect(&:facttext) 
	@factnum = @issue.facts.collect(&:factnum) 
	@facttext2 = @issue.facts.collect(&:facttext2) 
	@factnum2 = @issue.facts.collect(&:factnum2) 
	@factsource = @issue.facts.collect(&:factsource) 
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.all
		@facts = Fact.all
	end

	def show 
		@project = Project.find(params[:id])
	end

end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def is_active?(link_path)
  "active" if request.fullpath == link_path
end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/elements/TOP_navbar.BACKUP.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Actionable", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

<ul class="nav nav-pills" role="tablist">
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Issue <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
 <% Issue.all.each do |c| %>
  <li class="snavitem <%= is_active?(issue_path(c)) %>">
    <%= link_to "" + c.topic, issue_path(c) %>
  </li>
 <% end %>
    </ul>
  </li>
</ul>
  
</nav>

app/views/elements/_navbar.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:300,500' rel='stylesheet' type='text/css'>
  <link type="text/css" rel="stylesheet" href="/navbar.css">
</head> 

<body>
  <header>
    <div id="navbar" class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div class="collapse navbar-collapse navHeaderCollapse">
          <ul class="nav navbar-nav navbar-left" id="navbar_items">

                <li id="navlogo">
                  <%= link_to '/Actionable:', :root %>
                </li>

                <% Issue.all.each do |c| %>
                    <li class="snavitem <%= is_active?(issue_path(c)) %>">
                    <%= link_to "" + c.topic, issue_path(c) %>
                  <% end %>
                    </li>
                    
            </ul>
           </div>
            
        </div>

      </div>
    </div>
  </header>

</body>

app/views/elements/_navbarBACKUP.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
     <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %> 
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/issues/show.html.erb
<html>
	<head> 
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link type="text/css" rel="stylesheet" href="/viewpage.css">
		<link rel='http://fonts.googleapis.com/css?family=Titillium+Web:300, 500|Rockwell' rel='stylesheet' type='text/css'>

		<style>
		.jumbotron {
			background: url(<%= @issueimage %>) left center;
			background-position: 35% 25%;
		    -webkit-background-size: cover;
		    -moz-background-size: cover;
		    -o-background-size: cover;
		    background-size: cover;
		    background-repeat: no-repeat;
		    background-attachment: fixed;
		    background-color: #666666;
		    background-attachment: scroll;
		    max-width: 100%;
			height: auto;
			width: auto\9;
		}
		</style>

		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-57388340-1', 'auto');
		  ga('send', 'pageview');
		</script>

 	</head>


 	<body>
 				<!-- THIS IS THE ISSUE JUMBOTRON -->
		<div id="jumbotron" class="jumbotron">
			<div class="container">
				<h1 id="issue"><%= @issue.topic %></h1>
				<h1 id="chevron"><span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span></h1>
				<h3 id="photocredit">Photo Credit: <%= @issue.imageattribution %></h3>
			</div>
		</div>

				<!-- THIS IS THE ARTICLE SECTION -->
		<div id="jumbo-text-background" class="col-md-12"><!-- Article Content -->
			<div id="jumbo-text" class="col-md-8 col-centered">
				</br>
				<hr color="black" width="100%">
				<h2>In Recent News</h2>
				<a href="<%= @articleurl[0] %>" class="title" ><%= @articletitle[0] %></a>
				<hr color="black" width="100%">

				<!-- ADD .to_date back into @articledate when complete -->

				</br>
				<img src=<%= @articleimage[0] %> id="articlethumb" class="img-thumbnail">
				<p class="article-image-credit"><%= @articleimagecredit[0] %></p> 
				</br>
				</br>
				<p class="article-text"><%= @articlelead[0] %></p>
				</br>
				</br>
				<h3 class="publication">by 
				<%= @articleauthor[0] %> of 
				<%= @articlepublication[0] %>  
				</h3>
				<p class="article-date"><%= @articledate[0].to_date %></p>
				</br>
				<a href="<%= @articleurl[0] %>" class="btn btn-success btn-lg" id="articlebutton">Read More On <%= @issue.topic %></a>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
			</div>
		</div>	

						<!-- THIS IS THE FACTS SECTION -->
		<div id="project-facts-section" class="col-md-12">
			<div class="row row-centered" id="facts-row">
				<div class="col-md-7 col-centered" id="fact-columns">	
					<% (0..2).each do |i| %>
						<% if @facttext[i] == nil %>
							</br> 
						<% else %>
						<div id="facts-container" class="col-md-4">
							</br>
							<span id="factnum"><%= @factnum[i] %></span>
							</br>
							<span id="facttext"><%= @facttext[i] %></span>
							</br>
							<span id="factnum2"><%= @factnum2[i] %></span>
							</br>
							<span id="facttext2"><%= @facttext2[i] %></span>
							</br>
							<span id="factsource">Source: <%= @factsource[i] %></span>
						</div>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
						<!-- PADDING -->
		<div id="project-padding" class="col-md-12">
		</div>

						<!-- THIS IS THE PROJECT SECTION -->
		<div id="issue-project" class="col-md-12">
			<div id="issue-container" class="col-md-8 col-centered">
				<div id="project-text">
						</br>
						</br>
						
						<h2 id="actionable-today"> This Week's Action</h2>
						<hr color="black" width="100%">
						</br>
						<h3 id="projecttype"><%= @projecttype[0] %></h3>
						<a href="<%= @projecturl[0] %>" id="project-title"><%= @projecttitle[0] %></a>
						</br>
						</br>
						<img src=<%= @projectimage[0] %> id="projectthumb" class="img-circle">
						</br>
						<h3 id="project-org"><%= @projectorg[0] %></h3>
						</br>
						<p id="project-text"><%= @projectsumm[0] %></p>
						</br>
						</br>
						<a href="<%= @projecturl[0] %>" class="btn btn-danger btn-lg" id="projectbutton">Take Action</a>
						</br>
						</br>
						</br>
						</br>
						</br>
						</br>
				</div>
			</div>
		</div>

						<!-- THIS IS THE FOOTER -->
		
			<div id="foot" class="col-md-12">
				<div id="padding" class="col-md-12"></div>
				
				<h2 id="quote">"All that is necessary for the triumph of evil is that good men do nothing."</h2>
				<h2 id="quote"> -Edmund Burke</h2>
				</br>
				</br>
				<p id="foot-contact"><a href="mailto:chansd5@gmail.com?Subject=Hello%20Actionable" target="_top">By Sze Chan.</a></p>
				<p id="foot-logo">/Actionable. 2015. Made With Love In NYC.</p>
			</div>
		
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Actionable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<!-- Google Fonts -->
<link href='https://fonts.googleapis.com/css?family=Titillium+Web:300, 500' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Rockwell' rel='stylesheet' type='text/css'>

</head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link type="text/css" rel="stylesheet" href="/welcome.css">
		<link rel='http://fonts.googleapis.com/css?family=Titillium+Web:300, 500|Rockwell' rel='stylesheet' type='text/css'>

		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-57388340-1', 'auto');
		  ga('send', 'pageview');
		</script>
	
	</head>

	<body>
		<div id="jumbotron" class="jumbotron">
			<div class="container">
				<h1 id="logo">/Actionable:</h1>
				<h1 id="intro">Connecting News You Care About</h1>
				<h3 id="intro2">To The Projects That Help</h3>
			</div>
		</div>
		
		<!-- THIS IS THE FOOTER -->
		
			<div id="foot" class="col-md-12">
				<div id="padding" class="col-md-12"></div>
				
				<h2 id="quote">"All that is necessary for the triumph of evil is that good men do nothing."</h2>
				<h2 id="quote"> -Edmund Burke</h2>
				</br>
				</br>
				<p id="foot-contact"><a href="mailto:chansd5@gmail.com?Subject=Hello%20Actionable" target="_top">By Sze Chan.</a></p>
				<p id="foot-logo">/Actionable. 2015. Made With Love In NYC.</p>
			</div>
	</body>
</html>